//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProjectManager
    {
        public string EmployeeName { get; set; }
        public string ProjectName { get; set; }
        public string BusinessUnitName { get; set; }
    }
}
